# Generated by Django 4.0.4 on 2022-06-05 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lvl', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pay', models.IntegerField()),
                ('dep1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apip2.department')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.IntegerField()),
                ('area', models.CharField(max_length=50)),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apip2.clas')),
            ],
        ),
        migrations.AddField(
            model_name='clas',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apip2.teacher'),
        ),
    ]
