# Generated by Django 4.0.4 on 2022-06-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apip2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='dep1',
            new_name='dep',
        ),
    ]
