# Generated by Django 4.0.4 on 2022-08-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='normalize_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
