# Generated by Django 4.0.4 on 2022-06-03 17:53

import apip.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apip', '0004_alter_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='city',
            field=models.CharField(max_length=50, validators=[apip.models.validate_city]),
        ),
    ]
