# Generated by Django 4.0.4 on 2022-06-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apip', '0006_park'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='loc',
            field=models.IntegerField(),
        ),
    ]
