# Generated by Django 4.0.4 on 2022-06-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apip', '0007_alter_park_loc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park',
            name='id',
        ),
        migrations.AlterField(
            model_name='park',
            name='loc',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
